### PR TITLE
Added missing promise subscription

### PR DESCRIPTION
**Pull request by michielst**
## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by Aveek-Saha — COMMENTED** [review]
A callback was passed, so there is no need to add the .then

**Review by Aveek-Saha — COMMENTED** [review]
A callback was passed, so there is no need to add the .then

**Comment by michielst** [comment]
The callback doesn't get called on the latest version.

Method signature might have been updated?
image

Try clearing your storage and test again.

**Review by Aveek-Saha — CHANGES_REQUESTED** [review]
Looks like the function signature has indeed changed, if you add a catch for errors I can merge it.

**Pull request merged**
